spring.application.name=ratelimiter

#---DATABASE CONNECTION----
#This points to the db we created(ratelimiter_db)
spring.datasource.url = jdbc:postgresql://localhost:5432/ratelimiter_db
spring.datasource.username = postgres
spring.datasource.password = 120872
spring.datasource.driver-class-name = org.postgresql.Driver

#This creates the table for you automatically
spring.jpa.hibernate.ddl-auto = update
spring.jpa.show-sql = true